### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by nunojesus** [nattaponra/larawallet#1]
Hi, How are you?
Im a graphic designer that like to help projects in opensource for free, so if you like I can contribute with graphic designs,, I can make you a logotype for this project if you want. So if you need some design just say it.

Greetings!
Nuno Jesus

**Comment by nattaponra** [comment]
@nunojesus Yes, I need some logo.

**Comment by nattaponra** [comment]
@nunojesus  Now, I already invited you.
